### PR TITLE
Add polyfill for BigInt

### PR DESCRIPTION
**Pull request by lukasIO**
Thanks first of all for this project, it's exactly what I was looking for! 

This PR simply adds an option to polyfill `BigInt` to the rules.

### CODE REVIEW

**Comment by robatwilliams** [comment]
I didn't think BigInt could be polyfilled properly. This article agrees: https://javascript.info/bigint#polyfills

What are you using to polyfill it?

**Comment by robatwilliams** [comment]
Made me think - raised #71

**Comment by lukasIO** [comment]
A bit more context: 
I'm running the compat check on the bundled output of a TypeScript project.
A third party dependency of the lib is doing some checks like 
```js
if(globalThis.BigInt !== undefined) {
  // ... proceeds to reference BigInt
}
``` 
that _should_ be safe (as long as `globalThis` is actually polyfilled), but the es lint plugin complains. 
So I'm trying to work around it. 
Totally agree though that it's not really ideal as that would mask other occurences of `BigInt` to be wrongfully marked as polyfilled 🤔

**Comment by robatwilliams** [comment]
I see.

The problem of feature checks is a general one, but for all non-syntax features it can be worked around by stating that you have a polyfill (even if you don't actually). Except for things that aren't properly (or at all) polyfillable like BigInt here and probably ES2017 Atomics.

It might be possible to implement something [here](https://github.com/robatwilliams/es-compat/blob/master/packages/eslint-plugin-ecmascript-compat/lib/delegation.js#L28) to guess if an expression looks like a feature test. We have the AST node there. This feels like the proper way to solve the wider problem, which I'd like to try.

In the meantime perhaps you could use your code changes here via patch-package ?

**Comment by lukasIO** [comment]
To have proper support for detecting feature tests sounds ideal! 

Yeah, I'll work around it with a forked version for now, but very excited to see support for feature checks! 

Thanks for your feedback, will close this PR.

**Pull request closed without merging**
