### PR TITLE
Add a `recommended` config

### PR DESCRIPTION
**Pull request by brettz9**

### CODE REVIEW

**Comment by brettz9** [comment]
Thank you for the addition. Might you take a look at this one as well?

You can see some examples of other configs doing this at https://eslint.org/docs/developer-guide/working-with-plugins#configs-in-plugins (and many other plugins have such a feature).

**Comment by robatwilliams** [comment]
I'm on it as we speak :)

**Comment by robatwilliams** [comment]
Thanks. Few tweaks made as you can see above. I've now set up auto-build and required it to pass on PRs too.

**Comment by brettz9** [comment]
Apologies for the lazy means of adding on this one (through Github rather than setting up whole environment)--had a bunch of other similar changes across other repos and figured this was slight enough to avoid need for checks--but never is! :)

**Comment by robatwilliams** [comment]
No worries, makes sense.

Released: https://github.com/robatwilliams/es-compat/releases/tag/v1.1.0

**Pull request merged**
